version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - app-network

  robolab:
    build:
      context: ../
      dockerfile: dev.Dockerfile
      args:
        APP_PORT: 5455
    ports:
      - "5455:5455"
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - DB_PORT=5432
      - PORT=5455
      - ENVIRONMENT=dev
      - SECRET=your_secret_key
      - TOKEN_EXPIRE_TIME=24
      - DOMAIN_ID=your_domain_id
      - RESEND_API_KEY=your_resend_api_key
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
